package com.humpbacklab.letsfly

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class ApfpvFecDecoderTest {
    private val sourcePackets = arrayOf(
        byteArrayOf(1, 2, 3, 4),
        byteArrayOf(5, 6, 7, 8),
        byteArrayOf(9, 10, 11, 12),
        byteArrayOf(13, 14, 15, 16),
        byteArrayOf(17, 18, 19, 20),
        byteArrayOf(21, 22, 23, 24)
    )

    // Generated by the project's components/common/fec.cpp fec_new(6, 8).
    private val parityPackets = arrayOf(
        byteArrayOf(0xDF.toByte(), 0xDC.toByte(), 0xDD.toByte(), 0x97.toByte()),
        byteArrayOf(71, 68, 69, 29)
    )

    @Test
    fun restoresTwoMissingPrimaryPacketsFromReferenceZfecParity() {
        val decoder = ApfpvFecDecoder()
        val decoded = mutableListOf<ApfpvFecDecoder.DecodedPacket>()

        listOf(0, 2, 3, 5).forEach { index ->
            decoded += decoder.push(ApfpvProtocol.TransportPacket(42, index, sourcePackets[index]))
        }
        parityPackets.take(2).forEachIndexed { index, payload ->
            decoded += decoder.push(ApfpvProtocol.TransportPacket(42, 6 + index, payload))
        }

        assertEquals(6, decoded.size)
        sourcePackets.forEachIndexed { index, expected ->
            assertArrayEquals(expected, decoded[index].payload)
        }
        assertFalse(decoded[0].restoredByFec)
        assertTrue(decoded[1].restoredByFec)
        assertFalse(decoded[2].restoredByFec)
        assertFalse(decoded[3].restoredByFec)
        assertTrue(decoded[4].restoredByFec)
        assertFalse(decoded[5].restoredByFec)
    }

    @Test
    fun everySixOfEightPacketCombinationReconstructsTheBlock() {
        val allPackets = sourcePackets + parityPackets
        forEachCombination(8, 6) { selection ->
            val decoder = ApfpvFecDecoder()
            val decoded = mutableListOf<ApfpvFecDecoder.DecodedPacket>()
            selection.forEach { index ->
                decoded += decoder.push(ApfpvProtocol.TransportPacket(99, index, allPackets[index]))
            }

            assertEquals("selection=${selection.joinToString()}", 6, decoded.size)
            sourcePackets.forEachIndexed { index, expected ->
                assertArrayEquals("selection=${selection.joinToString()}, source=$index", expected, decoded[index].payload)
            }
        }
    }

    @Test
    fun retainsIncompleteBlockWhileLaterUdpBlockIsBeingReceived() {
        val decoder = ApfpvFecDecoder()
        val decoded = mutableListOf<ApfpvFecDecoder.DecodedPacket>()

        decoded += decoder.push(ApfpvProtocol.TransportPacket(42, 0, byteArrayOf(42, 0)))
        sourcePackets.forEachIndexed { index, payload ->
            decoded += decoder.push(ApfpvProtocol.TransportPacket(43, index, payload))
        }

        assertEquals(1, decoded.size)
        for (index in 1 until 6) {
            decoded += decoder.push(
                ApfpvProtocol.TransportPacket(42, index, byteArrayOf(42, index.toByte()))
            )
        }

        assertEquals(12, decoded.size)
        for (index in 0 until 6) {
            assertArrayEquals(byteArrayOf(42, index.toByte()), decoded[index].payload)
            assertArrayEquals(sourcePackets[index], decoded[index + 6].payload)
        }
    }

    private fun forEachCombination(size: Int, selectedCount: Int, callback: (IntArray) -> Unit) {
        val selected = IntArray(selectedCount)
        fun visit(start: Int, depth: Int) {
            if (depth == selectedCount) {
                callback(selected.copyOf())
                return
            }
            for (index in start..(size - selectedCount + depth)) {
                selected[depth] = index
                visit(index + 1, depth + 1)
            }
        }
        visit(0, 0)
    }
}
